Book.delete_all
orphantrain = Book.create("title" => "Orphan Train", "author" => "Christina Baker Kline", "price" => 26)
shadowspell = Book.create("title" => "Shadow Spell", "author" => "Nora Roberts", "price" => 15)
thealchemist = Book.create("title" => "The Alchemist", "author" => "Paulo Coelho", "price" => 12)
Book.create("title" => "King and Maxwell", "author" => "David Baldacci", "price" => 35)
Book.create("title" => "Whiskey Beach", "author" => "Nora Roberts", "price" => 22)
Book.create("title" => "A Game Of Thrones", "author" => "George R R Martin", "price" => 24)
Book.create("title" => "Americanah", "author" => "Chimamanda Ngozi Adichie", "price" => 20)
Book.create("title" => "Me Before You", "author" => "Jojo Moyes", "price" => 18)
Book.create("title" => "The Burgess Boys", "author" => "Elizabeth Strout", "price" => 15)
Book.create("title" => "The Interestings", "author" => "Meg Wolitzer", "price" => 27)
Book.create("title" => "Fly Away", "author" => "Kristin Hannah", "price" => 23)
Book.create("title" => "Beautiful Ruins", "author" => "Jess Walter", "price" => 14)
Book.create("title" => "The Light Between Oceans", "author" => "M L Stedman", "price" => 25)
Book.create("title" => "A Tale For The Time Being", "author" => "Ruth Ozeki", "price" => 34)
Book.create("title" => "Paris", "author" => "Edward Rutherford", "price" => 38)
Book.create("title" => "Beautiful Day", "author" => "Elin Hilderbrand", "price" => 16)
Book.create("title" => "Dark Places", "author" => "Gillian Flynn", "price" => 15)
Book.create("title" => "Four Friends", "author" => "Ron Carr", "price" => 20)
Book.create("title" => "The White Princess", "author" => "Philippa Gregory", "price" => 24)

Review.delete_all
Review.create(:bookid => orphantrain.id,:review => "Riveting!", :rating => 5)
Review.create(:bookid => orphantrain.id,:review => "About as dull as you can get.", :rating => 2)
Review.create(:bookid => orphantrain.id,:review => "Not bad.", :rating => 3)
Review.create(:bookid => shadowspell.id,:review => "Great book, and not too many pages.", :rating => 4)
Review.create(:bookid => shadowspell.id,:review => "Excellent font and margins.  Story wasn't bad, either.", :rating => 4)
Review.create(:bookid => shadowspell.id,:review => "Worth reading when there isn't a hockey game on.", :rating => 4)
Review.create(:bookid => shadowspell.id,:review => "Didn't understand it at all.", :rating => 1)
Review.create(:bookid => thealchemist.id,:review => "I thought this was about how to make gold?", :rating => 2)
Review.create(:bookid => thealchemist.id,:review => "Suspensful plot, good characters.", :rating => 4)
Review.create(:bookid => thealchemist.id,:review => "Perfect.  A work of art.", :rating => 5)
Review.create(:bookid => thealchemist.id,:review => "Kind of confusing.", :rating => 3)

puts "There are now #{Book.count} books, #{Review.count} reviews."